<?php
error_reporting(E_ERROR);
ini_set("display_errors",1);
//echo __LINE__ . "\n";
ob_start();
require_once('app_code/global.config.php');
require_once('class/config.inc.php');
require_once('class/class.email_client.php');
require_once('class/class.flags.php');
require_once('class/class.GlobalTask.php');
require_once('class/class.smtp.php');
require_once('class/class.tasks.php');
require_once('class/class.display.php');
require_once('class/class.casecreation.php');
require_once('class/class.dynamicpage.php');
require_once('class/class.contacts.php');
require_once('class/class.FctSearchScreen.php');
require_once('class/class.eapi_order.php');
require_once('class/class.eapi_account.php');
require_once('class/class.cases.php');
require_once('class/class.note.php');
require_once('class/class.knowledgebase.php');
require_once('class/class.welcome.php');
require_once('app_code/config.inc.php');
require_once( 'class/class.contacts.php');
require_once('app_code/zipcode.class.php');
require_once('app_code/class.Event_Contacts.php');
require_once('class/class.local_calendar.php');
ob_end_clean();
$casecreation = new case_creation();
$case = $_REQUEST['case_id'];
$data = $casecreation->get_case_data($case);
$use_data = array();
$use_data['case_id'] = $data['case_id'];
//$use_data['company_name'] = $data['company_name'];
//ini_set('display_errors' , 1 );
$font="freefont/FreeSansBold.ttf";
//header('Content-Type: image/gif');
require_once('class/class.qrcode.php');
require_once('class/class.print.php');
$qr = new QR(json_encode($use_data));
$image = $qr->image();
$qrsize = 140;
$img2 = imagecreatefromstring($image);
$img = imagecreatetruecolor($qrsize, $qrsize);
imagecopyresized($img, $img2, 0, 0, 0, 0, $qrsize, $qrsize, imagesx($img2), imagesy($img2));
$width=420;
$height=130;
$im = imagecreatetruecolor($width, $height);
$white = imagecolorallocate($im, 255, 255, 255);
$grey = imagecolorallocate($im, 128, 128, 128);
$black = imagecolorallocate($im, 0, 0, 0);
imagefilledrectangle($im, 0, 0, (int)$width - 1, (int)$height - 1, $white);
imagecopymerge ( $im , $img , 0 , 0 , 0  , 0 , $height  , $height  , 100 );
// Create some colors
//imagettftext($im, 12, 0, 150 , , $grey, $font, $order);
$height_offset = 8;
imagettftext($im, 12, 0, $height + 10, 30 + $height_offset , $black, $font,  "Case ID    : " . $data['case_id']);
imagettftext($im, 12, 0, $height + 10, 50 + $height_offset , $black, $font,  "Customer: " . substr($data['company_name'] , 0 , 22 ));
imagettftext($im, 12, 0, $height + 10 , 70 + $height_offset  , $black, $font,"Subject    : " . substr($data['subject'], 0 ,  22 ));

$im = imagerotate($im, 90, 0);
//$this->resize(100,$height);
ob_start();
imagegif($im);
$file=ob_get_contents();
ob_end_clean();
ob_start();
$print = new cups_print($file);
$print->print_doc();
ob_end_clean();
echo json_encode(array('status' => true));
//echo $file;
//imagegif($img);
//var_dump($size);
//echo $qr->image_res();
//echo imagegif( $qr->image_res() );
?>